[229318] Add documents for participants
access-company/IoTIntern pull request #12
Opened 2021-07-02 07:41 UTC by Fumipo-Theta

https://acsmine.tok.access-company.com/redmine/issues/229318

- 事前セットアップについて
- リモートマシンにVSCode拡張機能をインストールするスクリプト

`.vscode/settings.json`: VSCodeの設定ファイルではJSON記法が拡張されていてコメントに対応しています。

2021-07-08 01:26 UTC, aMasakiTakahashi commented on doc/for_participants/setup_ssh.md
> +
細かいですが、1行削除しましょう。
```suggestion
```

2021-07-08 01:33 UTC, aMasakiTakahashi commented on doc/for_participants/setup_ssh.md
> +  ![how to use Remote - SSH](./images/how_to_use_remote_ssh_extension.png)
図があると分かりやすいですね 👍

2021-07-08 01:34 UTC, hnishi requested changes
１点気がついた箇所を suggest しました。
それ以外は問題ないように思います。

2021-07-08 01:34 UTC, hnishi commented on doc/for_participants/setup_on_remote_machine.md
> +- [ElixirLS](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls) syntax highlightingや入力補完、定義の参照や定義箇所への移動ができるようになる
```suggestion
- [ElixirLS](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls): syntax highlightingや入力補完、定義の参照や定義箇所への移動ができるようになる
```

2021-07-08 01:37 UTC, hnishi commented on script/util/install_vscode_extensions.sh
> +  code --install-extension "${extension_name}.VSIX"
すみません。質問なのですが、このスクリプトはリモートマシン上で実行されると思いますが、code コマンドは vscode のリモート設定を行うと自動でインストールされるのでしょうか？

2021-07-08 01:40 UTC, aMasakiTakahashi approved these changes
LGTM!

2021-07-08 06:03 UTC, Fumipo-Theta commented on script/util/install_vscode_extensions.sh
> +  code --install-extension "${extension_name}.VSIX"
はい。正確には code-server というものがリモートにインストールされるのですが、それに伴って `code` コマンドが使用可能になります。

2021-07-08 06:37 UTC, hnishi commented on script/util/install_vscode_extensions.sh
> +  code --install-extension "${extension_name}.VSIX"
なるほどです。
ご回答ありがとうございます！

2021-07-08 06:40 UTC, hnishi approved these changes
ご対応ありがとうございます。
LGTM

2021-07-09 06:13 UTC, Fumipo-Theta commented
レビューありがとうございます。マージします。

2021-07-09 06:13 UTC, merged